/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LottoGUI.java
 *
 * Created on Jul 16, 2010, 2:43:43 PM
 */
package at.crkf.lotto;

import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.text.NumberFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author crkf
 */
public class LottoGUI extends javax.swing.JFrame {

    private class MyDispatcher implements KeyEventDispatcher {

        @Override
        public boolean dispatchKeyEvent(KeyEvent e) {
            if (e.getID() == KeyEvent.KEY_PRESSED) {
                if (e.getKeyCode() == KeyEvent.VK_ALT) {
                    cheat = true;
                    LottoGenerator.pcTipp(zahlen);
                    jButton3.setToolTipText("" + zahlen[0] + "  " + zahlen[1] + "  " + zahlen[2] + "  " + zahlen[3] + "  " + zahlen[4] + "  " + zahlen[5]);
                }
                if (e.getKeyCode() == KeyEvent.VK_SHIFT) {
                    cheat = false;
                    jButton3.setToolTipText("");
                }
            } else if (e.getID() == KeyEvent.KEY_RELEASED) {
            } else if (e.getID() == KeyEvent.KEY_TYPED) {
            }
            return false;
        }
    }
    int tipp[] = new int[6];
    int zahlen[] = new int[6];
    boolean cheat = false;

    /** Creates new form LottoGUI */
    public LottoGUI() {
        initComponents();

        KeyboardFocusManager manager = KeyboardFocusManager.getCurrentKeyboardFocusManager();
        manager.addKeyEventDispatcher(new MyDispatcher());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jftfTippZahl1 = new javax.swing.JFormattedTextField();
        jftfTippZahl2 = new javax.swing.JFormattedTextField();
        jftfTippZahl3 = new javax.swing.JFormattedTextField();
        jftfTippZahl4 = new javax.swing.JFormattedTextField();
        jftfTippZahl5 = new javax.swing.JFormattedTextField();
        jftfTippZahl6 = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lotto 6 aus 45");
        setMinimumSize(new java.awt.Dimension(375, 310));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipp"));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jftfTippZahl1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jftfTippZahl1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                checkValid(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 17;
        jPanel1.add(jftfTippZahl1, gridBagConstraints);

        jftfTippZahl2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jftfTippZahl2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                checkValid(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jftfTippZahl2, gridBagConstraints);

        jftfTippZahl3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jftfTippZahl3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                checkValid(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 17;
        jPanel1.add(jftfTippZahl3, gridBagConstraints);

        jftfTippZahl4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jftfTippZahl4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                checkValid(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 17;
        jPanel1.add(jftfTippZahl4, gridBagConstraints);

        jftfTippZahl5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jftfTippZahl5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                checkValid(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 17;
        jPanel1.add(jftfTippZahl5, gridBagConstraints);

        jftfTippZahl6.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jftfTippZahl6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                checkValid(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 17;
        jPanel1.add(jftfTippZahl6, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jTextArea1.setPreferredSize(new java.awt.Dimension(240, 150));
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButton3.setText("Tippen");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onTippen(evt);
            }
        });
        jPanel3.add(jButton3);

        jButton1.setText("QuickTipp");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onQuickTipp(evt);
            }
        });
        jPanel3.add(jButton1);

        jButton2.setText("Simulation");
        jButton2.setToolTipText("Solange tippen, bis ein Sechser erspielt wurde.");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onSimulation(evt);
            }
        });
        jPanel3.add(jButton2);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkValid(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_checkValid
        valid();

    }//GEN-LAST:event_checkValid

    private void onQuickTipp(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onQuickTipp

        LottoGenerator.pcTipp(tipp);

        jftfTippZahl1.setText("" + tipp[0]);
        jftfTippZahl2.setText("" + tipp[1]);
        jftfTippZahl3.setText("" + tipp[2]);
        jftfTippZahl4.setText("" + tipp[3]);
        jftfTippZahl5.setText("" + tipp[4]);
        jftfTippZahl6.setText("" + tipp[5]);

        calcLotto();
    }//GEN-LAST:event_onQuickTipp

    private void onTippen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onTippen
        if (valid()) {
            if (LottoGenerator.checkDublicates(tipp)) {
                JOptionPane.showMessageDialog(rootPane, "Doppelte Zahl vorhanden.");
            } else {
                calcLotto();
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Bitte überprüfen Sie die Eingabe!");
        }
    }//GEN-LAST:event_onTippen

    private void onSimulation(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onSimulation
        simulate();
    }//GEN-LAST:event_onSimulation

    public boolean valid() {
        boolean ok = true;

        if (!jftfTippZahl1.getText().equals("")) {
            tipp[0] = Integer.parseInt(jftfTippZahl1.getText().toString());
        } else {
            ok = false;
        }

        if (tipp[0] > 45 || tipp[0] <= 0) {
            jftfTippZahl1.setText("");
            ok = false;
        }

        if (!jftfTippZahl2.getText().equals("")) {
            tipp[1] = Integer.parseInt(jftfTippZahl2.getText().toString());
        } else {
            ok = false;
        }

        if (tipp[1] > 45 || tipp[1] <= 0) {
            jftfTippZahl2.setText("");
            ok = false;
        }


        if (!jftfTippZahl3.getText().equals("")) {
            tipp[2] = Integer.parseInt(jftfTippZahl3.getText().toString());
        } else {
            ok = false;
        }

        if (tipp[2] > 45 || tipp[2] <= 0) {
            jftfTippZahl3.setText("");
            ok = false;
        }

        if (!jftfTippZahl4.getText().equals("")) {
            tipp[3] = Integer.parseInt(jftfTippZahl4.getText().toString());
        } else {
            ok = false;
        }

        if (tipp[3] > 45 || tipp[3] <= 0) {
            jftfTippZahl4.setText("");
            ok = false;
        }

        if (!jftfTippZahl5.getText().equals("")) {
            tipp[4] = Integer.parseInt(jftfTippZahl5.getText().toString());
        } else {
            ok = false;
        }

        if (tipp[4] > 45 || tipp[4] <= 0) {
            jftfTippZahl5.setText("");
            ok = false;
        }

        if (!jftfTippZahl6.getText().equals("")) {
            tipp[5] = Integer.parseInt(jftfTippZahl6.getText().toString());
        } else {
            ok = false;
        }

        if (tipp[5] > 45 || tipp[5] <= 0) {
            jftfTippZahl6.setText("");
            ok = false;
        }
        return ok;
    }

    public void calcLotto() {
        jTextArea1.setText("");
        int richtige = 0;

        if (cheat) {
        } else {
            LottoGenerator.pcTipp(zahlen);
        }
        String zahlsort = LottoGenerator.sort(zahlen);

        jTextArea1.append("Die Lottozahlen dieser Ziehung lauten:\n" + zahlsort);

        jTextArea1.append("\n\nIhr Tipp:\n");
        for (int i = 0; i < 6; i++) {
            jTextArea1.append(tipp[i] + "  ");
        }

        richtige = LottoGenerator.vergleich(tipp, zahlen);

        jTextArea1.append("\n\nAnzahl der richtig getippten: " + richtige);

        if (cheat) {
            LottoGenerator.pcTipp(zahlen);
            jButton3.setToolTipText("" + zahlen[0] + "  " + zahlen[1] + "  " + zahlen[2] + "  " + zahlen[3] + "  " + zahlen[4] + "  " + zahlen[5]);

        } else {
        }
    }

    public void simulate() {
        jTextArea1.setText("");
        boolean ok;
        int richtige = 0, anzahlTipps = 0, anzahl3 = 0, anzahl4 = 0, anzahl5 = 0;

        LottoGenerator.pcTipp(zahlen);

        String zahlsort = LottoGenerator.sort(zahlen);

        jTextArea1.append("Die Lottozahlen dieser Ziehung lauten:\n" + zahlsort);

        do {
            ok = true;
            ++anzahlTipps;
            LottoGenerator.pcTipp(tipp);
            richtige = LottoGenerator.vergleich(tipp, zahlen);

            if (richtige == 6) {
                ok = false;
            }

            if (richtige == 3) {
                ++anzahl3;
            }

            if (richtige == 4) {
                ++anzahl4;
            }

            if (richtige == 5) {
                ++anzahl5;
            }
        } while (ok == true);

        jftfTippZahl1.setText("" + tipp[0]);
        jftfTippZahl2.setText("" + tipp[1]);
        jftfTippZahl3.setText("" + tipp[2]);
        jftfTippZahl4.setText("" + tipp[3]);
        jftfTippZahl5.setText("" + tipp[4]);
        jftfTippZahl6.setText("" + tipp[5]);

        jTextArea1.append("\n\nAnzahl der nötigen Versuche: " + NumberFormat.getIntegerInstance().format(new Integer(anzahlTipps)));
        jTextArea1.append("\n\nDabei zusätzlich erspielt:\n"
                + "5er: " + NumberFormat.getIntegerInstance().format(new Integer(anzahl5)) + "\n"
                + "4er: " + NumberFormat.getIntegerInstance().format(new Integer(anzahl4)) + "\n"
                + "3er: " + NumberFormat.getIntegerInstance().format(new Integer(anzahl3)) + "\n");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new LottoGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JFormattedTextField jftfTippZahl1;
    private javax.swing.JFormattedTextField jftfTippZahl2;
    private javax.swing.JFormattedTextField jftfTippZahl3;
    private javax.swing.JFormattedTextField jftfTippZahl4;
    private javax.swing.JFormattedTextField jftfTippZahl5;
    private javax.swing.JFormattedTextField jftfTippZahl6;
    // End of variables declaration//GEN-END:variables
}
